### ISSUE TITLE
Seeking Maintainers

### ISSUE THREAD

**Issue by kingdido999** [kingdido999/zooming#144]
While this is the most interesting, fulfilling and rewarding open-source project that I've ever worked on, as time goes by, I find myself lacking motivation and bandwidth to maintain this project. 

If you're interested in maintaining this project, feel free to introduce yourself and let me know why would you want to do so. You don't have to be an expert of JavaScript or anything, but some basic working knowledge of JS and DOM APIs is expected. 

Of course, I will help you with the transition if you have any questions. Thanks!

**Comment by mahish** [comment]
@kingdido999 I dont have much time neither but I like this project a lot and since Ive already contributed (#51) Im willing to help you or someone else to maintain it. Recently, Ive started to make single-page app with VueJS so I want to make it work together (there are some strange glitches and the whole code will need to rewrite probably). That's my TODO for April.

**Comment by kingdido999** [comment]
@mahish Glad to hear that! Keep me updated then 😸
