### ISSUE TITLE
Strange behavior when zoom animation is activated

### ISSUE THREAD

**Issue by theEMA-dev** [kingdido999/zooming#313]
When i click a image element to zoom, all my elements slide down. Its very disturbing.

**To Reproduce**
1. go to https://theema-dev.github.io/highRES/
2. scroll down to second or third row.
3. click a image to zoom in.

**Expected behavior**
I expect to everything stays static.

**Desktop**
 - OS: Windows 10
 - Browser [chrome, edge]
 - Version [newest]

**Comment by kingdido999** [comment]
I tested your website in Chrome and Firefox on MacOS but everything seems fine. Unfortunately I don't have Windows 10 to test this out. Could you confirm the issue is reproducible in Firefox as well? Also do you see any error message from the dev console? It might also be helpful if you show me how you setup the Zooming instance.

**Comment by theEMA-dev** [comment]
It seems fine in firefox. I cant see any error at console in Chrome or Edge. You can check my instance here;
**html :** https://gist.github.com/theEMA-dev/62d784c5e9be00c71bf815d773b32614
**css :** https://gist.github.com/theEMA-dev/a52eea9a2229adb8b97608a923c04ebe

**Comment by kingdido999** [comment]
They look fine to me. It may be related to browser/OS, but unfortunately I could not debug further. I'll add a label to this issue in case someone could help with this issue.
