### ISSUE TITLE
Wrong zoomed image position from fixed container

### ISSUE THREAD

**Issue by artaommahe** [kingdido999/zooming#34]
I see an issue in page:
https://codepen.io/anon/pen/eWyEGR?editors=1010

OS: Ubuntu 16.04 (64-bit)
Browser and version: Chromium Version 58.0.3029.81

Steps to reproduce:

1. open codepen example
2. scroll one screen down
3. zoom image
4. see that it has wrong position

Use-case: fixed chat container with images in messages that can be zoomed when page is scrolled down.
Mb fixed position for zoomed image?

**Comment by kingdido999** [comment]
I probably will end up adding a fixed wrapper to image, which I believe will address this issue and #22 as well...Having `position: relative` on image is giving me so much headache :(

**Comment by kingdido999** [comment]
Update: a fixed position wrapper with absolute image position and an image placeholder (since the actual image no longer takes space) does resolve these issues (`position: fixed and overflow: hidden` parents). Everything works fine except that while the image is getting closed on scrolling, the translation does not go to the precise position that takes scroll offset into account (though eventually it goes back to the correct position...). I guess this could be fixed somehow, but I haven't found a solution yet.

**Comment by kingdido999** [comment]
Opened an issue to keep track of adding image wrapper #44.

**Comment by kingdido999** [comment]
I don't intend to find a fix at this point. I'll accept it as a known issue and mention it in the README.
