### ISSUE TITLE
Remove listeners

### ISSUE THREAD

**Issue by larafale** [kingdido999/zooming#45]
Hello Guys, I'm using react and my component can be rendered multiple times.
I instanciate in `componentDidMount` like this `(new Zooming()).listen('.zommable')`
So how can I remove/clean all previous listeners before re rendering ? thanks

**Comment by kingdido999** [comment]
Short answer: there is no public API to remove all the listeners and you probably don't need to.

I would suggest using the same zooming instance within `componentDidMount` instead of creating a new one every time. Please take a look at this example: https://github.com/kingdido999/atogatari/blob/master/client/src/components/ZoomableImage.js

The exact same event listener does not stack, i.e., add the same event listener multiple times will just be ignored.

**Comment by larafale** [comment]
@kingdido999 Thanks a lot for the link
