### ISSUE TITLE
Can you zoom within an element? 

### ISSUE THREAD

**Issue by patrickbjohnson** [kingdido999/zooming#48]
Considering using this but the demo only displays a zoom interaction in which the image is clicked and then zoomed over the entire document width. 

Curious if there is any possibility of being able to zoom within an element like a `div` with a defined height/width?

**Comment by kingdido999** [comment]
Hmm...interesting. Unfortunately, it does not support such functionality. In what scenario do you think this kind of use case is useful?

**Comment by mahish** [comment]
Do you mean something like this? https://codepen.io/mahish/pen/NAQpyB Usually, it is used in eshops for example. I dont know the codebase but I find such functionality for different package since it has different purpose (two different design patterns: lightbox vs. zoom). It would be nice they could be plugable tho.

**Comment by kingdido999** [comment]
I will close it since the thread is no longer active.
