### ISSUE TITLE
Loading zooming.js with head.js does not seem to work

### ISSUE THREAD

**Issue by p-4** [kingdido999/zooming#63]
I am not sure what is causing the issue. I follow advice online on how to load a .js file conditionally.
I would like to load zooming.js only on devices with a screen bigger than a certain amount of pixels, or another condition.

In this first test I load zooming.js with `<script></script>` inside the html and it works fine.
https://codepen.io/zuhocuyixu/pen/oqpdWz

In this second test I try to load zooming.js with head.js with no conditions at all, just to load it.
https://codepen.io/zuhocuyixu/pen/XEVEwG

And it does not work. Instead of head.js I also tried lazyload.js and the result is the same.

Trying to load a .css file with the same code works okay.

Any advice on why the second test does not load the zooming feature for the images?

**Comment by kingdido999** [comment]
Unfortunately, I don't have any advice for this issue after some investigation. I would rather not dig further for two reasons:

1.  It's not a feature issue related to zooming itself.
2. I might be wrong, but I'm not sure about if there's any benefit from loading our library in `<head>` since zooming only starts listening to images after [DOM content is fully loaded](https://github.com/kingdido999/zooming/blob/master/src/index.js#L4).

**Comment by p-4** [comment]
@kingdido999 Thank you for checking this.

How would you advice to make it so, that zooming is not laded on devices with a screen smaller than certain width in pixels?

Would you please specify what method I should research on achieving this?

Thank you

**Comment by p-4** [comment]
Posting this for future reference for the less experienced (like me) on how to load zooming conditionally.

In this case on screens bigger than certain amount of pixels.

Here is the original question:
https://stackoverflow.com/questions/49572604/loading-a-js-file-conditionally-how

And here the final result. Loads zooming if browser window width is more than 500px:
https://codepen.io/zuhocuyixu/pen/wmmyOZ
