### ISSUE TITLE
The page becomes a blank after zooming

### ISSUE THREAD

**Issue by potoo0** [kingdido999/zooming#96]
- URL to reproduce the issue: https://codepen.io/potoo/pen/yRxrZe
- OS: Windows
- Browser and version: Chrome: 69.0.3497.100

If the grid has both position and z-index properties (the properties generated by the theme I use), then the page will be blank after clicking the image, it looks like the image is below the `<div>` generated by zoom.js, but after I increase the z-index of img, it is still the same situation.

Could you help me figure it out? Thanks.

**Comment by kingdido999** [comment]
One potential workaround is by setting the grid z-index to a value greater than the zooming overlay z-index: https://codepen.io/anon/pen/yRxmmO

This issue is related to [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context). In the top level stacking context, grid div has `z-index: 0` and zooming overlay div has `z-index: 998` by default. Obviously, grid is below the overlay. But the image z-index is greater than the overlay z-index, why isn't the image showing above the overlay? Because the image is a child of the grid, the image z-index is only relative to the grid's stacking context, which is irrelevant to overlay's stacking context. So as long as the grid z-index is less than the overlay z-index, the image will not show up properly.

**Comment by potoo0** [comment]
Oh. I get it. Sincerely thank you for your answer.

**Comment by potoo0** [comment]
In this case, the contents of the grid will showing just below the image after the image is zoomed. Is there has any way to make the overlay take effect on grid?

[CodePen demo](https://codepen.io/potoo/pen/ePPMYM)

And I got another situation: The `DOMContentLoaded` event isn't fired when my page has full loaded, so zoom.js will not execute. Unless I refresh the page.

中文:
这样做的话，会使图片放大之后 grid 的内容显示在后面，有办法让 zoom 之后只看到图片，覆盖 grid 的内容吗？[CodePen 演示](https://codepen.io/potoo/pen/ePPMYM)
 em...
 然后我还有另一个问题，有时我的页面无法检测到 DOMContentLoaded 事件，不会执行zoom.js。这时必须要刷新才能正常加载 zoom.js。您可以也帮我看下这个问题吗？

**Comment by kingdido999** [comment]
Try this: https://codepen.io/kingdido999/pen/jeXgBZ

For the second question, since it is not related to this library, I suggest you to search for answer elsewhere or post question on stackoverflow with actual code so people can help you.

**Comment by potoo0** [comment]
OK, thanks
